### PR TITLE
Fix build scripts

### LINKED ISSUE #102: Unit tests failing with `aiohttp>=v3.10.0`
Since version `v3.10.0` of `aiohttp`, inside `_create_direct_connection`, the `_wrap_create_connection()` method is no longer called with a `host` and `port`.

NEW: https://github.com/aio-libs/aiohttp/blob/v3.10.0/aiohttp/connector.py#L1281-L1290
OLD: https://github.com/aio-libs/aiohttp/blob/v3.9.5/aiohttp/connector.py#L1226-L1239

This breaks our unit tests:

```python
======================================================================
test_connect_pass_timeout (tribler.test_unit.core.socks5.test_aiohttp_connector.TestSocks5Connector) ... ERROR

======================================================================
ERROR: test_connect_pass_timeout (tribler.test_unit.core.socks5.test_aiohttp_connector.TestSocks5Connector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\unittest\async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\unittest\async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\unittest\async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "D:\a\TriblerExperimental\TriblerExperimental\src\tribler\test_unit\core\socks5\test_aiohttp_connector.py", line 84, in test_connect_pass_timeout
    self.connection = await self.connector.connect(ClientRequest("GET", URL("http://localhost/")), [],
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\aiohttp\connector.py", line 546, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\aiohttp\connector.py", line 954, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\aiohttp\connector.py", line 1282, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
TypeError: _wrap_create_connection() missing 2 required positional arguments: 'host' and 'port'

----------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by egbertbouman**
This PR fixes the build scripts that were broken after merging https://github.com/qstokkink/TriblerExperimental/pull/82.

Also fixes https://github.com/qstokkink/TriblerExperimental/issues/102.

### CODE REVIEW

**Comment by egbertbouman** [comment]
validate

**Review by qstokkink — APPROVED** [review]

**Comment by egbertbouman** [comment]
validate
